package utils

import (
	"bufio"
	"io"
	"os"

	"github.com/fsouza/go-dockerclient"
)

// attach attaches to the container
func attach(client *docker.Client, container *docker.Container) error {
	r, w := io.Pipe()
	options := docker.AttachToContainerOptions{
		Container:    container.ID,
		OutputStream: w,
		ErrorStream:  w,
		Stream:       true,
		Stdout:       true,
		Stderr:       true,
		Logs:         true,
	}
	log.Info("Attaching to container " + container.ID)
	go client.AttachToContainer(options)
	go func(reader io.Reader, container *docker.Container) {
		scanner := bufio.NewScanner(reader)
		for scanner.Scan() {
			log.Info("%s%s \n", container.ID, scanner.Text())
		}
		if err := scanner.Err(); err != nil {
			log.Error("There was an error with the scanner in attached container", err)
		}
	}(r, container)
	return nil
}

// ContainerDeploy Deploys a container  wich option are specified by config. Optional arguments are passed, typicallyf autogenerated by processor/preprocessor
func ContainerDeploy(config *Config, args []string, volumes []string, head string) (bool, error) {
	endpoint := "unix:///var/run/docker.sock"
	client, _ := docker.NewClient(endpoint)
	var containerconfig *docker.Config
	var err error
	var status int
	DockerImage := config.DockerImage

	if config.DockerSkipPull == false {
		log.Info("Pulling image: %s\n", DockerImage)

		if err := client.PullImage(docker.PullImageOptions{Repository: DockerImage}, docker.AuthConfiguration{}); err != nil {
			log.Error("error pulling %s image: %s\n", DockerImage, err)
			return false, err
		}
	}
	combinedArgs := append(args, config.Args...)
	if len(config.DockerImageEntrypoint) == 0 {
		containerconfig = &docker.Config{
			Image: DockerImage,
			Cmd:   combinedArgs,
			Env:   config.Env,
		}
	} else {
		containerconfig = &docker.Config{
			Image:      DockerImage,
			Cmd:        combinedArgs,
			Env:        config.Env,
			Entrypoint: config.DockerImageEntrypoint,
		}
	}

	container, err := client.CreateContainer(docker.CreateContainerOptions{
		Config: containerconfig,
	})

	attach(client, container)
	// Cleanup when done
	defer func() {
		if config.DockerCommit == true {
			repository, repositoryok := config.Commit["repository"]
			tag, tagok := config.Commit["tag"]
			message, messageok := config.Commit["message"]
			author, authorok := config.Commit["author"]
			on, onok := config.Commit["on"]
			if tagok == false {
				tag = "latest"
			}
			if messageok == false {
				message = ""
			}
			if authorok == false {
				author = ""
			}
			if onok == false {
				on = "always"
			}
			log.Info("Committing to " + repository + " \n\tTag:" + tag + " Message: " + message + " Author: " + author)

			if repositoryok {

				if onok {
					switch on {
					case "success":
						if status == int(0) {
							Image, err := client.CommitContainer(docker.CommitContainerOptions{
								Container:  container.ID,
								Repository: repository,
								Message:    message,
								Author:     author,
								Tag:        tag,
								Run:        containerconfig,
							})
							if err != nil {
								log.Error(err.Error())
							} else {
								log.Info("Image committed to ID: " + Image.ID)
							}
						}
					default:
						Image, err := client.CommitContainer(docker.CommitContainerOptions{
							Container:  container.ID,
							Repository: repository,
							Message:    message,
							Author:     author,
							Tag:        tag,
							Run:        containerconfig,
						})
						if err != nil {
							log.Error(err.Error())
						} else {
							log.Info("Image committed to ID: " + Image.ID)
						}
					}
				} else {
					Image, err := client.CommitContainer(docker.CommitContainerOptions{
						Container:  container.ID,
						Repository: repository,
						Message:    message,
						Author:     author,
						Tag:        tag,
						Run:        containerconfig,
					})
					if err != nil {
						log.Error(err.Error())
					} else {
						log.Info("Image committed to ID: " + Image.ID)
					}
				}
			} else {
				log.Error("You haven't defined at least a repository to commit in inside your configuration file")
			}
		}
		client.RemoveContainer(docker.RemoveContainerOptions{
			ID:    container.ID,
			Force: true,
		})
	}()
	if err != nil {
		log.Error(err.Error())
	}
	log.Info("Starting container: " + container.ID)
	volumes = append(volumes, config.Volumes...)
	err = client.StartContainer(container.ID, &docker.HostConfig{Binds: volumes, LogConfig: docker.LogConfig{Type: "json-file"}})
	if err != nil {
		log.Error(err.Error())
		return false, err
	}
	status, err = client.WaitContainer(container.ID)
	container, err = client.InspectContainer(container.ID) // update our container information
	if err != nil {
		log.Error(err.Error())
	}

	logfile := config.LogDir + "/" + head + ".json"
	log.Debug("Copying " + container.LogPath + " to " + logfile)
	err = CopyFileContents(container.LogPath, logfile)
	os.Chmod(logfile, os.FileMode(config.LogPerm))
	if err != nil {
		log.Error(err.Error())
	}

	if status == int(0) {
		return true, err
	}
	return false, err

}
